### ISSUE TITLE
Python3  support

### ISSUE THREAD

**Issue by pablo33** [pablo33/quodlibet-filesorter#6]
It seems that python3 is the new standard python environment shipped with ubuntu 20.04. Need to revise the code to python3.

It seems that quodlibet installation comes with python3 libraries and python2 libraries have been deprecated.

Error:

```
  Quod-libet config file found.
Running, have a good time. 
	Loginlevel: INFO
	Logging to: ./filegroupping.log
Traceback (most recent call last):
  File "quodlibet_filesorter.py", line 320, in <module>
    songs = cPickle.load(songsfile)
ImportError: No module named quodlibet.formats.mp3
```

**Comment by pablo33** [comment]
DATADIR = os.path.join(os.getenv("XDG_DATA_HOME", HOME, ".local", "share"), 'quolibet')
CONFIDIR = os.path.join(os.getenv("XDG_CONFIG_HOME", HOME, ".config")), 'quolibet')
CACHEDIR = os.path.join(os.getenv("XDG_CACHE_HOME", HOME, ".cache")), 'quolibet')

songs file has been moved???
check it

 https://github.com/quodlibet/quodlibet/issues/138

**Comment by pablo33** [comment]
> DATADIR = os.path.join(os.getenv("XDG_DATA_HOME", HOME, ".local", "share"), 'quolibet')
> CONFIDIR = os.path.join(os.getenv("XDG_CONFIG_HOME", HOME, ".config")), 'quolibet')
> CACHEDIR = os.path.join(os.getenv("XDG_CACHE_HOME", HOME, ".cache")), 'quolibet')
> 
> songs file has been moved???
> check it
> 
> [quodlibet/quodlibet#138](https://github.com/quodlibet/quodlibet/issues/138)

Nothing to do, the 'songs' file is already at this place.

**Comment by pablo33** [comment]
Using Python 3.8.2 

```
>>> cPickle  
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
NameError: name 'cPickle' is not defined  

```
It seems there is no module **cPickle** on the library. Need to install or it has change it's name.

**Comment by pablo33** [comment]
Tried with python3 and **pickle**, same code
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

```
Line 329:
`fullpathfilename = str.decode(str(element('~filename')),'utf8')`

Need song object testing and instrospection

**Comment by pablo33** [comment]
from:
[https://groups.google.com/forum/#!topic/quod-libet-development/UMzvLIEjuwI](https://groups.google.com/forum/#!topic/quod-libet-development/UMzvLIEjuwI
)

tried with no success:

`from quodlibet.formats import load_audio_files, dump_audio_files 
`
```


>>> load_audio_files('/home/pablo/.quodlibet/songs',True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/quodlibet/formats/_serialize.py", line 121, in load_audio_files
    items = pickle_loads(data, lookup_func)
  File "/usr/lib/python3/dist-packages/quodlibet/util/picklehelper.py", line 119, in pickle_loads
    return pickle_load(BytesIO(data), lookup_func=lookup_func)
TypeError: a bytes-like object is required, not 'str'

```

**Comment by pablo33** [comment]
Trying :  [https://groups.google.com/forum/#!topic/quod-libet-development/peq_2i4TVmk](https://groups.google.com/forum/#!topic/quod-libet-development/peq_2i4TVmk)

**Comment by pablo33** [comment]
Try to find something there:

[https://groups.google.com/forum/#!forum/quod-libet-development](https://groups.google.com/forum/#!forum/quod-libet-development
)

**Comment by pablo33** [comment]
Well, just thinking re-writting code for python3 and use this utility to read tags:
[https://pypi.org/project/mp3-tagger/](https://pypi.org/project/mp3-tagger/)

This should allow sort files without quodlibet.

**Comment by pablo33** [comment]
Nop, allowed tags are limited.
Lets see this
[http://pyid3lib.sourceforge.net/doc.html](http://pyid3lib.sourceforge.net/doc.html)

**Comment by pablo33** [comment]
Maybe too old, let's see eye3D
`pip3 install eyeD3`

**Comment by pablo33** [comment]
```
for a in audiofile.tag.frameiter():
     print (a.id)

b'TALB'
b'TCMP'
b'TCON'
b'TIT2'
b'TPE1'
b'TXXX'
b'XRVA'
```
Quodlibet Frame is **b'TXXX'**

```
for a in audiofile.tag.frameiter():
    print (a.data)


b'\x03QuodLibet::filegroupping\x00~/Compilations/[<labelid> - ][<album>/][CD<discnumber> -][<tracknumber> - ][<artist> - ]<title>.<ext>\x00'

```

```
for a in audiofile.tag.frameiter():
    print (a.render())

b'TXXX\x00\x00\x00\x7f\x00\x00\x03QuodLibet::filegroupping\x00~/Compilations/[<labelid> - ][<album>/][CD<discnumber> -][<tracknumber> - ][<artist> - ]<title>.<ext>'

```

**Comment by pablo33** [comment]
Coded on branch toeyed3
